import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Hakkımızda | Minatoi'nin Hikâyesi",
  description: "Minatoi'nin cam tablo üretim anlayışını, kalite yaklaşımını ve yaşam alanlarına sanat katma vizyonunu keşfedin.",
};

const features = ["4 mm temperli cam kullanıyoruz", "UV baskı teknolojisi ile canlı ve solmayan renkler elde ediyoruz", "Yıllar boyunca ilk günkü görünümünü koruyan yüzeyler sunuyoruz"];

export default function StoryPage() {
  return <><Header/><main className="story-page"><section className="story-hero"><span>MINATOI'NİN HİKÂYESİ</span><h1>Camın içindeki<br/><em>sanat.</em></h1><p>Yaşam alanlarının sadece birer mekân değil, aynı zamanda duygu ve karakter yansıması olduğuna inanıyoruz.</p></section><section className="story-intro"><div><span>HAKKIMIZDA</span><h2>Bir dekorasyon ürününden daha fazlası.</h2></div><div><p>Minatoi olarak ürettiğimiz her cam tabloyu, bulunduğu ortama anlam katan ve ruh veren bir tasarım parçası olarak görüyoruz.</p><blockquote>Kuruluş amacımız çok net: Sanatı herkes için ulaşılabilir, kaliteli ve uzun ömürlü hale getirmek.</blockquote></div></section><section className="story-dark"><div className="story-number">01</div><div><span>NE YAPIYORUZ?</span><h2>Modern üretim.<br/>Seçilmiş estetik.</h2><p>Minatoi’da modern üretim teknikleri ile estetik tasarımı bir araya getiriyoruz. Her tasarım, seçilmiş bir estetik anlayışın ve titiz bir üretim sürecinin sonucudur.</p><ul>{features.map(x=><li key={x}>{x}</li>)}</ul></div></section><section className="glass-reason"><div><span>02 · NEDEN CAM TABLO?</span><h2>Çünkü cam,<br/>ışığı yansıtır.</h2><p>Derinlik katar. Bulunduğu ortamı sıradanlıktan çıkarır.</p></div><div className="glass-card"><p>Kağıt ya da kanvas baskıların aksine cam yüzey:</p><strong>daha parlak</strong><strong>daha net</strong><strong>daha dayanıklıdır</strong><small>Biz de bu farkı en iyi şekilde sunmak için çalışıyoruz.</small></div></section><section className="art-view"><span>03 · SANAT ANLAYIŞIMIZ</span><h2>Tek bir tarz yok.<br/><em>Çünkü herkes farklı.</em></h2><p>Koleksiyonlarımızda minimal tasarımları, soyut eserleri, modern grafikleri, doğa ve manzara temalarını bir araya getiriyoruz. Amacımız herkesin kendine ait bir parça bulabilmesi.</p><div className="art-tags"><b>Minimal</b><b>Soyut</b><b>Modern</b><b>Doğa</b></div></section><section className="quality"><div><span>04 · KALİTE VE GÜVEN</span><h2>Satış sadece<br/>bir başlangıçtır.</h2></div><div className="quality-list"><article><b>01</b><h3>Güvenli paketleme</h3><p>Her sipariş yolculuğa özel korumalı olarak çıkar.</p></article><article><b>02</b><h3>Hasarsız teslimat</h3><p>Kırılma riskine karşı teslimat garantisi sunarız.</p></article><article><b>03</b><h3>Gerçek memnuniyet</h3><p>Müşterilerimizi her şeyin önünde tutarız.</p></article></div></section><section className="vision"><span>VİZYONUMUZ</span><h2>Yaşam alanlarına<br/>değer katan bir marka.</h2><p>Kaliteyi düşürmeden, estetikten ödün vermeden ve müşteriye gerçekten değer vererek ilerliyoruz.</p><hr/><blockquote>Evinizdeki bir duvar, doğru bir dokunuşla sıradanlıktan çıkabilir. Biz de tam olarak bu dokunuşu sunmak için buradayız.</blockquote><b>Minatoi — Camın içindeki sanat.</b></section></main><Footer/></>;
}
