"use client";
import { ChangeEvent, DragEvent, useRef, useState } from "react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { formatPrice } from "@/app/data";

const sizes = [{label:"25 × 35 cm",price:610,min:"2400 × 3400 px"},{label:"35 × 50 cm",price:790,min:"3400 × 4800 px"},{label:"50 × 70 cm",price:1190,min:"4800 × 6700 px"},{label:"60 × 90 cm",price:1590,min:"5700 × 8600 px"}];

export default function DirectPrintPage(){
  const [size,setSize]=useState(0); const [orientation,setOrientation]=useState<"portrait"|"landscape">("portrait"); const [file,setFile]=useState<File|null>(null); const input=useRef<HTMLInputElement>(null);
  const choose=(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null);
  const drop=(e:DragEvent)=>{e.preventDefault();setFile(e.dataTransfer.files?.[0]||null)};
  return <><Header/><main className="direct-page direct-page-immediate"><section className="customizer"><div className="upload-panel"><div className="customizer-title"><span>01</span><div><h2>Fotoğrafınızı yükleyin</h2><p>Ölçü ve yönü belirleyip görselinizi ekleyin.</p></div></div><div className="config-block"><div className="config-label"><b>Tablo ölçüsü</b><span>{formatPrice(sizes[size].price)}</span></div><div className="config-buttons">{sizes.map((x,i)=><button className={size===i?"active":""} onClick={()=>setSize(i)} key={x.label}>{x.label}</button>)}</div></div><div className="config-block"><div className="config-label"><b>Yön seçimi</b></div><div className="config-buttons orientation-buttons"><button className={orientation==="portrait"?"active":""} onClick={()=>setOrientation("portrait")}>▯ Dikey</button><button className={orientation==="landscape"?"active":""} onClick={()=>setOrientation("landscape")}>▭ Yatay</button></div></div><div className={`dropzone ${file?"has-file":""}`} onDragOver={e=>e.preventDefault()} onDrop={drop} onClick={()=>input.current?.click()}><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/>{file?<><b>✓ {file.name}</b><span>Değiştirmek için tıklayın veya yeni dosyayı sürükleyin</span></>:<><strong>Fotoğrafınızı buraya sürükleyin</strong><span>veya</span><button type="button">Dosya seç</button><small>JPG, PNG veya WEBP · En fazla 25 MB</small></>}</div><div className="custom-add"><div className="qty-static">1</div><button disabled={!file}>Sepete ekle · {formatPrice(sizes[size].price)} →</button></div><p className="privacy">🔒 Fotoğrafınız yalnızca siparişinizin üretimi için kullanılır ve üçüncü kişilerle paylaşılmaz.</p></div><aside className="photo-guide"><article><span>FOTOĞRAF BOYUTU</span><h3>Net baskı için yüksek çözünürlük.</h3><p>Seçtiğiniz <b>{sizes[size].label}</b> ölçüsü için önerilen minimum görsel boyutu:</p><strong>{sizes[size].min}</strong><small>{orientation==="portrait"?"Dikey baskıda görselin boyu daha uzun olmalıdır.":"Yatay baskıda görselin genişliği daha uzun olmalıdır."}</small></article><article><span>FOTOĞRAF İPUÇLARI</span><h3>En iyi sonuç için</h3><ul><li>Yüz, obje ve kompozisyon net olmalı.</li><li>Yumuşak ve dengeli gün ışığını tercih edin.</li><li>Görseliniz seçtiğiniz yöne uygun olmalı.</li><li>Ekran görüntüsü yerine orijinal dosyayı yükleyin.</li><li>Portrelerde yüzün tamamı kadrajda olmalı.</li></ul></article><div className="guide-features"><b>UV baskı</b><b>Solmayan renkler</b><b>Kolay temizlik</b></div></aside></section></main><Footer/></>;
}
