/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as IndexRouteImport } from './routes/index'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/urunler': typeof UrunlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/urunler': typeof UrunlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/urunler': typeof UrunlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/urunler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/urunler'
  id: '__root__' | '/' | '/urunler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UrunlerRoute: typeof UrunlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UrunlerRoute: UrunlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
