/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as PatiliDosyalaraOzelRouteImport } from './routes/patili-dosyalara-ozel'
import { Route as OdemeSonucuRouteImport } from './routes/odeme-sonucu'
import { Route as MesafeliSatisSozlesmesiRouteImport } from './routes/mesafeli-satis-sozlesmesi'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as KullaniciSozlesmesiRouteImport } from './routes/kullanici-sozlesmesi'
import { Route as KisiyeOzelRouteImport } from './routes/kisiye-ozel'
import { Route as IptalIadeRouteImport } from './routes/iptal-iade'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UrunSlugRouteImport } from './routes/urun.$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const PatiliDosyalaraOzelRoute = PatiliDosyalaraOzelRouteImport.update({
  id: '/patili-dosyalara-ozel',
  path: '/patili-dosyalara-ozel',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeSonucuRoute = OdemeSonucuRouteImport.update({
  id: '/odeme-sonucu',
  path: '/odeme-sonucu',
  getParentRoute: () => rootRouteImport,
} as any)
const MesafeliSatisSozlesmesiRoute = MesafeliSatisSozlesmesiRouteImport.update({
  id: '/mesafeli-satis-sozlesmesi',
  path: '/mesafeli-satis-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const KullaniciSozlesmesiRoute = KullaniciSozlesmesiRouteImport.update({
  id: '/kullanici-sozlesmesi',
  path: '/kullanici-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const KisiyeOzelRoute = KisiyeOzelRouteImport.update({
  id: '/kisiye-ozel',
  path: '/kisiye-ozel',
  getParentRoute: () => rootRouteImport,
} as any)
const IptalIadeRoute = IptalIadeRouteImport.update({
  id: '/iptal-iade',
  path: '/iptal-iade',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const UrunSlugRoute = UrunSlugRouteImport.update({
  id: '/urun/$slug',
  path: '/urun/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/iptal-iade': typeof IptalIadeRoute
  '/kisiye-ozel': typeof KisiyeOzelRoute
  '/kullanici-sozlesmesi': typeof KullaniciSozlesmesiRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/odeme-sonucu': typeof OdemeSonucuRoute
  '/patili-dosyalara-ozel': typeof PatiliDosyalaraOzelRoute
  '/sepet': typeof SepetRoute
  '/urunler': typeof UrunlerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/iptal-iade': typeof IptalIadeRoute
  '/kisiye-ozel': typeof KisiyeOzelRoute
  '/kullanici-sozlesmesi': typeof KullaniciSozlesmesiRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/odeme-sonucu': typeof OdemeSonucuRoute
  '/patili-dosyalara-ozel': typeof PatiliDosyalaraOzelRoute
  '/sepet': typeof SepetRoute
  '/urunler': typeof UrunlerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/iptal-iade': typeof IptalIadeRoute
  '/kisiye-ozel': typeof KisiyeOzelRoute
  '/kullanici-sozlesmesi': typeof KullaniciSozlesmesiRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/odeme-sonucu': typeof OdemeSonucuRoute
  '/patili-dosyalara-ozel': typeof PatiliDosyalaraOzelRoute
  '/sepet': typeof SepetRoute
  '/urunler': typeof UrunlerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/gizlilik-politikasi'
    | '/iletisim'
    | '/iptal-iade'
    | '/kisiye-ozel'
    | '/kullanici-sozlesmesi'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/odeme-sonucu'
    | '/patili-dosyalara-ozel'
    | '/sepet'
    | '/urunler'
    | '/blog/$slug'
    | '/kategori/$slug'
    | '/urun/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/gizlilik-politikasi'
    | '/iletisim'
    | '/iptal-iade'
    | '/kisiye-ozel'
    | '/kullanici-sozlesmesi'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/odeme-sonucu'
    | '/patili-dosyalara-ozel'
    | '/sepet'
    | '/urunler'
    | '/blog/$slug'
    | '/kategori/$slug'
    | '/urun/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/gizlilik-politikasi'
    | '/iletisim'
    | '/iptal-iade'
    | '/kisiye-ozel'
    | '/kullanici-sozlesmesi'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/odeme-sonucu'
    | '/patili-dosyalara-ozel'
    | '/sepet'
    | '/urunler'
    | '/blog/$slug'
    | '/kategori/$slug'
    | '/urun/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  IletisimRoute: typeof IletisimRoute
  IptalIadeRoute: typeof IptalIadeRoute
  KisiyeOzelRoute: typeof KisiyeOzelRoute
  KullaniciSozlesmesiRoute: typeof KullaniciSozlesmesiRoute
  KvkkRoute: typeof KvkkRoute
  MesafeliSatisSozlesmesiRoute: typeof MesafeliSatisSozlesmesiRoute
  OdemeSonucuRoute: typeof OdemeSonucuRoute
  PatiliDosyalaraOzelRoute: typeof PatiliDosyalaraOzelRoute
  SepetRoute: typeof SepetRoute
  UrunlerRoute: typeof UrunlerRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  UrunSlugRoute: typeof UrunSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patili-dosyalara-ozel': {
      id: '/patili-dosyalara-ozel'
      path: '/patili-dosyalara-ozel'
      fullPath: '/patili-dosyalara-ozel'
      preLoaderRoute: typeof PatiliDosyalaraOzelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme-sonucu': {
      id: '/odeme-sonucu'
      path: '/odeme-sonucu'
      fullPath: '/odeme-sonucu'
      preLoaderRoute: typeof OdemeSonucuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesafeli-satis-sozlesmesi': {
      id: '/mesafeli-satis-sozlesmesi'
      path: '/mesafeli-satis-sozlesmesi'
      fullPath: '/mesafeli-satis-sozlesmesi'
      preLoaderRoute: typeof MesafeliSatisSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanici-sozlesmesi': {
      id: '/kullanici-sozlesmesi'
      path: '/kullanici-sozlesmesi'
      fullPath: '/kullanici-sozlesmesi'
      preLoaderRoute: typeof KullaniciSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisiye-ozel': {
      id: '/kisiye-ozel'
      path: '/kisiye-ozel'
      fullPath: '/kisiye-ozel'
      preLoaderRoute: typeof KisiyeOzelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptal-iade': {
      id: '/iptal-iade'
      path: '/iptal-iade'
      fullPath: '/iptal-iade'
      preLoaderRoute: typeof IptalIadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/urun/$slug': {
      id: '/urun/$slug'
      path: '/urun/$slug'
      fullPath: '/urun/$slug'
      preLoaderRoute: typeof UrunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  IletisimRoute: IletisimRoute,
  IptalIadeRoute: IptalIadeRoute,
  KisiyeOzelRoute: KisiyeOzelRoute,
  KullaniciSozlesmesiRoute: KullaniciSozlesmesiRoute,
  KvkkRoute: KvkkRoute,
  MesafeliSatisSozlesmesiRoute: MesafeliSatisSozlesmesiRoute,
  OdemeSonucuRoute: OdemeSonucuRoute,
  PatiliDosyalaraOzelRoute: PatiliDosyalaraOzelRoute,
  SepetRoute: SepetRoute,
  UrunlerRoute: UrunlerRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  UrunSlugRoute: UrunSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
